receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: "*"
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
processors:
  batch:
  metricstransform:
    transforms:
    - include: .*
      match_type: regexp
      action: update
      operations:
        action: add_label
        new_label: tool
        new_value: analyzer
    - include: .*
      match_type: regexp
      action: update
      operations:
        action: add_label
        new_label: product
        new_value: oneapi_compiler
    - include: .*
      match_type: regexp
      action: update
      operations:
        action: add_label
        new_label: source
        new_value: engineer
    - include: .*
      match_type: regexp
      action: update
      operations:
        action: add_label
        new_label: source
        new_value: build_tool      
exporters:
  # logging:
  #   loglevel: debug
  datadog:
    api:
      key: _DD_API_KEY_
service:
  # telemetry:
  #   logs:
  #     level: debug
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [metricstransform, batch]
      # exporters: [datadog, logging]
      exporters: [datadog]
    # traces: 
    #   receivers: [otlp]
    #   exporters: [datadog, logging]
