receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: "*"
  hostmetrics:
    scrapers:
      load:
      memory:
      network:
processors:
    batch:
exporters:
  datadog:
    api:
      key: _API_KEY_
service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [datadog]
    traces: 
      receivers: [otlp]
      exporters: [datadog]