version: '3.9'
services:
  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.52.0
    container_name: otel-datadog
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yml
    ports:
      - "4317"
      - "4318"
   

  # OpenTelemetry Metric Simple
  otelmetric:
    container_name: otel-metric-example
    build: ./
    depends_on:
      - otelcol