version: '3.9'
services:
  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.52.0
    container_name: otel-col
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./src/otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317"
      - "4318"
    depends_on:
      - helloworld

  # HelloWorld
  helloworld:
    environment: 
      - ENABLE_METRICS_PREVIEW
    image: helloworld-cpp
    build: ./

